name: Deploy static content to Pages

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Bun for frontend
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install frontend dependencies and build project
      - name: Install Dependencies
        working-directory: ./frontend
        run: bun install

      - name: Build Frontend
        working-directory: ./frontend
        run: bun run build

      # Deploy built frontend files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist